// 03-navigation-ia.md §1 — Rail 1 kategorileri (veri-tabanlı; engine bunları bilmez)
export const CATEGORIES = [
  { id: "egitim", label: "Eğitim Yolu", icon: "ph-graduation-cap", order: 0, section: "BAŞLANGIÇ" },
  { id: "genel", label: "Genel Harita", icon: "ph-list-checks", order: 1, section: "BAŞLANGIÇ" },
  { id: "kernel", label: "Kernel — Layer 0", icon: "ph-cube", order: 2, section: "İNŞA SIRASI" },
  { id: "scale", label: "Scale Primitives", icon: "ph-trend-up", order: 3, section: "İNŞA SIRASI" },
  { id: "layer1", label: "Layer 1 — In-tree", icon: "ph-stack", order: 4, section: "İNŞA SIRASI" },
  { id: "stack", label: "Stack Ürünleri", icon: "ph-package", order: 5, section: "İNŞA SIRASI" },
  { id: "urunler", label: "Ürün Modülleri", icon: "ph-squares-four", order: 7, section: "REFERANS" },
  { id: "crosscut", label: "Çapraz-Kesen", icon: "ph-arrows-out", order: 8, section: "REFERANS" },
  { id: "dx", label: "DX & Services", icon: "ph-puzzle-piece", order: 10, section: "REFERANS" },
  { id: "build", label: "Build & Deploy", icon: "ph-flag-banner", order: 6, section: "İNŞA SIRASI" },
  { id: "backend", label: "Backend Tech-Stack", icon: "ph-database", order: 9, section: "REFERANS" },
  { id: "frontend", label: "Frontend Tech-Stack", icon: "ph-device-mobile", order: 11, section: "REFERANS" },
  { id: "sus", label: "Sürdürülebilirlik", icon: "ph-infinity", order: 12, section: "REFERANS" },
];

// Dosya prefix → kategori (07A §2; istisnalar tek tabloda)
export const PREFIX_TO_CATEGORY = {
  edu: "egitim",
  kernel: "kernel",
  k: "kernel",
  scale: "scale",
  layer1: "layer1",
  l1: "layer1",
  stack: "stack",
  dist: "stack", // Distribution = sektör paketi; stack kategorisinde ayrı grup (03 §2)
  s: "urunler",
  cc: "crosscut",
  crosscut: "crosscut",
  sus: "sus",
  fe: "frontend",
  landx: "stack", // LandX top-level değil — Stack Ürünleri altında vaka (sahibinden clone)
  edition: "stack",
  be: "backend",
  dx: "dx",
  services: "dx",
  deploy: "build",
  build: "build",
  file: "build",
  product: "build",
  anti: "build",
};

// Tekil meta dosyalar → genel (02-icerik-envanteri.md)
export const STEM_OVERRIDES = {
  overview: "genel",
  philosophy: "genel",
  "board-rebuilt": "genel",
  "atomic-types": "kernel", // Faz 0 — İnşa Sırası'nın sıfırıncı adımı (03 §1); eski genel/ linki stem-fallback ile sağ
};

// urunler kategorisinin Rail 2 grupları — 00-overview'daki 9 ürün kategorisi (03 §2)
export const PRODUCT_GROUPS = [
  { id: "op", label: "Çekirdek Operasyon" },
  { id: "fin", label: "Finans & Muhasebe" },
  { id: "scm", label: "Tedarik Zinciri & Lojistik" },
  { id: "hr", label: "İnsan Kaynakları" },
  { id: "cx", label: "Müşteri & Gelir" },
  { id: "content", label: "İçerik & İşbirliği" },
  { id: "data", label: "Veri & Zeka" },
  { id: "platform", label: "Platform & Altyapı" },
  { id: "vertical", label: "Dikey Çözümler" },
  { id: "diger", label: "Diğer" },
];

export const PRODUCT_GROUP_MAP = {
  crm: "op",
  sales: "op",
  pos: "op",
  inventory: "op",
  purchase: "op",
  "ecommerce-models": "op",
  dropshipping: "op",
  "subscription-commerce": "op",
  "social-commerce": "op",
  classifieds: "op",
  billing: "fin",
  "revenue-recognition": "fin",
  "subscription-analytics": "fin",
  fpa: "fin",
  expenses: "fin",
  "fixed-assets": "fin",
  treasury: "fin",
  consolidation: "fin",
  "tax-compliance": "fin",
  "payment-methods": "fin",
  wms: "scm",
  tms: "scm",
  fleet: "scm",
  "demand-planning": "scm",
  procurement: "scm",
  quality: "scm",
  cmms: "scm",
  traceability: "scm",
  fsm: "scm",
  payroll: "hr",
  ats: "hr",
  onboarding: "hr",
  performance: "hr",
  workforce: "hr",
  clm: "cx",
  cpq: "cx",
  loyalty: "cx",
  pim: "cx",
  marketplace: "cx",
  dms: "content",
  wiki: "content",
  community: "content",
  event: "content",
  survey: "content",
  membership: "content",
  rag: "data",
  bi: "data",
  etl: "data",
  observability: "data",
  predictive: "data",
  "doc-matching": "data",
  conversational: "data",
  studio: "data",
  bpm: "platform",
  ipaas: "platform",
  iam: "platform",
  audit: "platform",
  i18n: "platform",
  comms: "content",
  mail: "content",
  scheduling: "content",
  "channel-hub": "op",
  esign: "cx",
  isg: "hr",
  kvkk: "platform",
  iot: "data",
  property: "vertical",
  education: "vertical",
  clinic: "vertical",
  restaurant: "vertical",
  incentive: "vertical",
  legaltech: "vertical",
};
